# components/00-namespace-rbac/spark-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-sa
  namespace: bigdata
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: bigdata
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: bigdata
subjects:
- kind: ServiceAccount
  name: spark-sa
  namespace: bigdata
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
