# components/03-trino/trino-values-full.yaml
#
# Full values file for installing Trino using the official Helm chart (trino/trino).
# Version: Corresponding to chart 1.38.0 / app version 474 (or 1.39.0 / 475 if updated)
#
# Key configurations:
# - Connects to external Hive Metastore (ilum chart deployment)
# - Connects to external Minio using Native S3 FS and credentials from a secret
# - Enables http-server.process-forwarded for Traefik compatibility
# - Disables Helm chart's Ingress creation (will be created manually)

# --- Base Image Settings ---
# Helm will typically use the appVersion from the Chart.yaml (e.g., 474 or 475)
# Ensure this matches the chart version being installed (1.38.0 or 1.39.0)
image:
  repository: trinodb/trino
  # tag: "475" # Explicitly set tag if needed, otherwise uses chart's appVersion
  pullPolicy: IfNotPresent

# --- Coordinator Configuration ---
coordinator:
  # Adjust resources as needed for your cluster
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  # Other coordinator specific settings (JVM, config, etc.) can be added here if needed

# --- Worker Configuration ---
worker:
  replicas: 2 # Number of worker nodes
  # Adjust resources as needed for your cluster
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  # Other worker specific settings (JVM, config, etc.) can be added here if needed

# --- Catalog Configuration ---
# Defines connection properties for data sources
catalogs:
  # --- Hive Connector Configuration ---
  hive: |
    # Use the standard Hive connector name
    connector.name=hive
    # URI for the Hive Metastore service deployed earlier
    hive.metastore.uri=thrift://ilum-hive-metastore.bigdata.svc.cluster.local:9083

    # --- Native S3 Filesystem Configuration (for Minio) ---
    # Enable the native S3 filesystem support
    fs.native-s3.enabled=true
    # Internal service endpoint for your Minio deployment
    s3.endpoint=http://minio.minio.svc.cluster.local:9000
    # Required for Minio and other non-AWS S3 implementations
    s3.path-style-access=true
    # S3 credentials sourced from environment variables (injected via envFrom)
    s3.aws-access-key=${env:MINIO_ACCESS_KEY}
    s3.aws-secret-key=${env:MINIO_SECRET_KEY}
    # Dummy region often required by AWS SDK even for compatible storage
    s3.region=us-east-1

  # --- Standard Test Catalogs (Optional) ---
  tpch: |
    connector.name=tpch
  tpcds: |
    connector.name=tpcds

# --- Environment Variables from Secrets ---
# Injects secrets into all Trino pods (coordinator and workers)
# Used by the S3 configuration in the hive catalog above
envFrom:
  - secretRef:
      # Name of the Kubernetes secret holding Minio credentials
      name: minio-s3-secret

# --- Additional Trino Configuration Properties ---
# Added to config.properties on all nodes
additionalConfigProperties:
  # Allow Trino to process X-Forwarded-* headers from Traefik Ingress
  - "http-server.process-forwarded=true"
  # Add any other global config properties here if needed
  # Example: - "query.max-memory=10GB"

# --- Ingress Configuration (DISABLED) ---
# Set enabled to false because the chart's Ingress template had issues.
# A separate, manual Ingress manifest will be applied.
ingress:
  enabled: false

# --- Default Security Contexts (from chart defaults) ---
# These are generally compatible with the 'baseline' Pod Security Standard
# securityContext:
#   runAsUser: 1000
#   runAsGroup: 1000
# containerSecurityContext:
#   allowPrivilegeEscalation: false
#   capabilities:
#     drop:
#       - ALL

# --- Other Sections (Defaults or Customize as needed) ---
# service:
#   type: ClusterIP
#   port: 8080
# serviceAccount:
#   create: false
#   name: ""
# accessControl: {}
# resourceGroups: {}
# jmx:
#   enabled: false
# serviceMonitor:
#   enabled: false
# networkPolicy:
#   enabled: false
# etc.
