# components/02-hive-metastore/ilum-metastore-values.yaml
#
# Values file for deploying Hive Metastore using the 'ilum/ilum-hive-metastore' Helm chart.
# Configured to use an external PostgreSQL database deployed in the 'bigdata' namespace
# and Minio for the default warehouse location.

# --- Image Configuration ---
# Uses the default image provided by the chart (ilum/hive:3.1.3 as of chart 1.1.0)
# You can override if needed:
# image: custom-registry/custom-hive:tag
# pullPolicy: IfNotPresent

# --- Resource Allocation ---
# Adjust requests and limits based on expected load and cluster resources
resources:
  requests:
    cpu: "200m"    # Initial CPU request
    memory: "512Mi" # Initial Memory request
  limits:
    memory: "1Gi"  # Memory limit

# --- PostgreSQL Database Configuration ---
# Configure connection to the external PostgreSQL instance deployed previously
postgresql:
  # Hostname of the PostgreSQL service within the 'bigdata' namespace
  host: postgres-svc.bigdata.svc.cluster.local
  # Standard PostgreSQL port
  port: 5432
  # Database name created for Hive Metastore
  database: hive_metastore
  # --- Authentication ---
  # Username defined in the 'postgres-bigdata-secret'
  auth:
    username: hiveuser
    # IMPORTANT: Password and Minio keys are passed via --set during helm install/upgrade
    # due to limitations in this chart version (no existingSecret support for these fields).
    # Ensure you run helm install/upgrade with:
    # --set postgresql.auth.password=$PG_PASSWORD \
    # --set storage.s3.accessKey=$MINIO_ACCESS_KEY \
    # --set storage.s3.secretKey=$MINIO_SECRET_KEY
    # where variables hold values from 'postgres-bigdata-secret' and 'minio-s3-secret'.
    password: "" # Leave empty here, will be overridden by --set

# --- Metastore Warehouse Storage Configuration ---
# Configures Minio/S3 as the default location for table data
storage:
  # Type of storage backend
  type: s3
  # --- Default Warehouse Directory ---
  metastore:
    # IMPORTANT: Replace '<your-minio-bucket>' with the actual bucket name in your Minio.
    # It's recommended to create a dedicated bucket (e.g., 'hive-warehouse').
    # The 's3a://' prefix is crucial for S3-compatible storage.
    warehouse: s3a://<your-minio-bucket>/warehouse/
  # --- S3 Specific Configuration ---
  s3:
    # Internal service endpoint for Minio within the cluster
    host: minio.minio.svc.cluster.local
    # Standard Minio API port
    port: 9000
    # IMPORTANT: Access Key and Secret Key are passed via --set during helm install/upgrade
    accessKey: "" # Leave empty here, will be overridden by --set
    secretKey: "" # Leave empty here, will be overridden by --set

# --- Service Configuration ---
# Configures how the Hive Metastore service is exposed within the cluster
service:
  # Use ClusterIP as it only needs to be accessed by Trino/Spark within the cluster
  type: ClusterIP
  # Default Thrift port for Hive Metastore
  port: 9083

# --- Init Schema Job ---
# Parameters for the Job that initializes the database schema (usually leave defaults)
# postgresql:
#  initSchemaJob:
#    ... # Default values are likely sufficient

# --- Additional hive-site.xml configurations ---
# Can be used to add extra properties if needed, but the basics
# are covered by the specific postgresql and storage sections above.
# conf:
#   hiveSite:
#     - some.hive.property: value
